# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v3 # uses package.json packageManager

    - uses: actions/setup-node@v3
      with:
        node-version: '*' # https://github.com/actions/setup-node#supported-version-syntax
        cache: 'pnpm'

    - run: pnpm install --frozen-lockfile

    - name: write .env
      run: |
        cat << EOF > .env
        DATABASE_URL='mysql://fake?sslaccept=strict'
        NEXTAUTH_SECRET=n
        NEXTAUTH_URL=http://localhost:3000
        TWITCH_CLIENT_ID=c
        TWITCH_CLIENT_SECRET=s
        EOF

    - run: pnpm run lint
